scss_files: 'src/main/sass/*.scss'

exclude: 'src/main/sass//compass/**'

linters:
  HexNotation:
    style: uppercase

  Indentation:
    severity: warning
    character: tab
    width: 1

  LeadingZero:
    style: include_zero

