# Rules for stylelint
# http://stylelint.io/?/docs/user-guide/rules.md

rules:
  at-rule-empty-line-before: null
  at-rule-no-vendor-prefix: true

  block-opening-brace-newline-before: "always-multi-line"
  block-opening-brace-newline-after: "always-multi-line"
  block-opening-brace-space-before: "always-single-line"
  block-opening-brace-space-after: "always-single-line"
  block-closing-brace-newline-before: "always-multi-line"
  block-closing-brace-newline-after: "always-multi-line"
  block-closing-brace-space-before: "always-single-line"
  block-closing-brace-space-after: "always-single-line"
  block-no-empty:
    - true
    -
      warn: true

  color-hex-case: "upper"
  color-hex-length: null
  color-no-hex: null
  color-no-invalid-hex: true
  color-no-named: null

  comment-empty-line-before: null
  comment-whitespace-inside:
    - "always"
    -
      warn: true

  custom-property-no-outside-root: true
  custom-property-pattern: null

  declaration-bang-space-before: "always"
  declaration-bang-space-after: "never"
  declaration-block-semicolon-newline-before: "never-multi-line"
  declaration-block-semicolon-newline-after: "always-multi-line"
  declaration-block-semicolon-space-before: "never"
  declaration-block-semicolon-space-after: "always-single-line"
  declaration-colon-newline-after: "always-multi-line"
  declaration-colon-space-before: "never"
  declaration-colon-space-after: "always-single-line"
  declaration-no-important: null

  function-calc-no-unspaced-operator: true
  function-comma-newline-before: "never-multi-line"
  function-comma-newline-after: "always-multi-line"
  function-comma-space-before: "never"
  function-comma-space-after: "always-single-line"
  function-linear-gradient-no-nonstandard-direction: true
  function-parentheses-newline-inside: null
  function-parentheses-space-inside: "never"
  function-url-quotes: "double"
  function-blacklist: null
  function-whitelist: null

  indentation: "tab"
  max-line-length: 120

  media-feature-colon-space-before: "never"
  media-feature-colon-space-after: "always"
  media-feature-name-no-vendor-prefix: true
  media-feature-range-operator-space-before: "always"
  media-feature-range-operator-space-after: "always"
  media-query-list-comma-newline-before: "never-multi-line"
  media-query-list-comma-newline-after: "always-multi-line"
  media-query-list-comma-space-before: "never"
  media-query-list-comma-space-after: "always-single-line"
  media-query-parentheses-space-inside: "never"
  custom-media-pattern: null

  no-eol-whitespace: true
  no-missing-eof-newline: true

  number-leading-zero: "always"
  number-max-precision: 2
  number-no-trailing-zeros: true
  number-zero-length-no-unit: true

  property-no-vendor-prefix: true
  property-blacklist: null
  property-whitelist: null
  property-unit-blacklist: null
  property-unit-whitelist: null

  root-no-standard-properties: true

  rule-nested-empty-line-before: null
  rule-no-duplicate-properties: true
  rule-no-shorthand-property-overrides: true
  rule-non-nested-empty-line-before: null
  rule-properties-order: null
  rule-trailing-semicolon: "always"

  selector-combinator-space-before: "always"
  selector-combinator-space-after: "always"
  selector-list-comma-newline-before: "never-multi-line"
  selector-list-comma-newline-after: "always"
  selector-list-comma-space-before: "never"
  selector-list-comma-space-after: "always-single-line"
  selector-no-attribute: null
  selector-no-combinator: null
  selector-no-id: null
  selector-no-type: null
  selector-no-universal: null
  selector-no-vendor-prefix: true
  selector-pseudo-element-colon-notation: "double"
  selector-root-no-composition: true
  selector-class-pattern: null
  selector-id-pattern: null

  string-quotes: "double"

  unit-blacklist: null
  unit-whitelist: null

  value-list-comma-newline-before: "never-multi-line"
  value-list-comma-newline-after: "always-multi-line"
  value-list-comma-space-before: "never"
  value-list-comma-space-after: "always-single-line"
  value-no-vendor-prefix: true
